#!/bin/bash

sudo apt-get -y update
sudo apt-get install python2.7
sudo apt-get install -y python-pip
sudo apt-get install -y python-software-properties 
sudo apt-get install -y build-essential
sudo apt-get install -y libpq-dev
sudo apt-get install -y libxml2-dev libxslt-dev  python-dev  python-setuptools
sudo pip install -r requirements.txt
export TOKEN="263651123:AAHUqH6y-q2WCu5gkvKQ5PrrBhUKQ_9D0BU"
export USER_BD="dvrvjtupxbpjbs"
export PASS_BD="enzqVLw1_CnTvtacmB2uFEzo16"
